[build]
  base = "frontend"
  command = "npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  ESLINT_NO_DEV_ERRORS = "true"

[[redirects]]
  from = "/api/*"
  to = "${RENDER_BACKEND_URL}/api/:splat"
  status = 200

[[redirects]]
  from = "/ws/*"
  to = "wss://${RENDER_BACKEND_URL_WS}/ws/:splat"
  status = 200
